# Change these first
owner: Dealsafee # Your GitHub organization or username, where this repository lives
repo: ds-uptime # The name of this repository

sites:
  - name: Dealsafe
    url: https://dealsafe.in

# assignees: # Users to assign downtime issues (optional)
#   - Dealsafee
  
status-website: # Status website (optional)
  baseUrl: /ds-uptime
  name: Upptime # Status website title
